version: '2'
volumes:
    dev_volume:
        driver: local
services:
    main: &main
        build: .
        depends_on:
         - mongo
        ports:
         - "80:3000"
        environment:
            MONGO_URI: 'mongodb://mongo/nchu-lib'
        restart: always
    dev:
        <<: *main
        entrypoint: []
        ports:
         - "80:3000"
        command: bash
        volumes_from:
         - dev_volume
        volumes:
         - .:/workspace
    dev_volume:
        build: .
        ports: []
        volumes:
         - dev_volume:/service
        command: echo true
    rsync:
        image: uvatbc/rsync
        user: root
        volumes_from:
         - dev_volume
        volumes:
         - .:/workspace
        command: rsync --exclude=node_modules --exclude=.git --exclude=*.swp -urv --delete /workspace/ /service
    mongo:
        image: mongo
    backup: &backup_restore
        image: mongo
        depends_on:
         - mongo
        volumes:
         - .:/workspace
        working_dir: /workspace
        command: bash -c "mongodump -h mongo --out backup/$$(date +%Y%m%d%H%M%S)"
    restore: 
        <<: *backup_restore
        entrypoint: ["mongorestore", "-h", "mongo"]
        command: []

